# Site specific settings
title: "Clojure UG Home Page"
name: "Clojure UG"
keywords: "clojure,clojurescript,iranclojure"
baseurl: ""
url: "http://iranclojure.ir"
description: "TODO"
cover: "/assets/img/cover.svg"
fanpage_id: ""

# Site general settings
lang: "en"
ssl: false # It will redirect to https

# Media
# Just the shortname:
# facebook: lampiaosec # Rigth
# facebook: facebook.com/lampiaosec # Wrong
#disqus: test
twitter:
facebook:
github: //github.com/karajlug/
google:

# Build settings
markdown: kramdown
permalink: /:categories/:title/
